title: Cake Factory
name: Cake Factory
base_url: /cakefactory
url: http://127.0.0.1:4000/
remote_url: https://jillii.github.io/cakefactory/

collections:
  - sections

plugins:
  - jekyll-commonmark

publilsh_mode: editorial_wordflow

backend:
  name: github
  repo: jillii/cakefactory # Path to your GitHub repository
  open_authoring: true