# config.yml

backend:
  name: github
  repo: jillii/cakefactory # Path to your GitHub repository
  open_authoring: true

media_folder: 'assets/images'

publish_mode: editorial_workflow

collections:
  - name: sections
    label: sections
    folder: '_sections/'
    fields:
      - { name: title }
      - { name: weight }
      - { name: output }